# Generated by Django 5.0.4 on 2024-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0002_rename_geneticalgorithmconfiguration_geneticalgorithmresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticalgorithmresult',
            name='date',
            field=models.DateField(),
        ),
    ]
