# Generated by Django 5.0.4 on 2024-04-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0003_alter_geneticalgorithmresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticalgorithmresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
