# Generated by Django 5.0.4 on 2024-04-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0004_alter_geneticalgorithmresult_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneticalgorithmresult',
            old_name='mutation_probability',
            new_name='mutation_rate',
        ),
    ]
