# Generated by Django 5.0.4 on 2024-04-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0005_rename_mutation_probability_geneticalgorithmresult_mutation_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneticalgorithmresult',
            old_name='average_time',
            new_name='total_time',
        ),
        migrations.RemoveField(
            model_name='geneticalgorithmresult',
            name='maximum_time',
        ),
    ]
