# Generated by Django 5.0.4 on 2024-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0008_geneticalgorithmresult_tournament_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticalgorithmresult',
            name='tournament_size',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
