# Generated by Django 5.0.4 on 2024-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_genetic_algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='RealGeneticAlgorithmResult',
            name='tournament_size',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
